SELECT * from Employee order by First_name ASC;
SELECT * from Employee order by First_name DESC;
SELECT * from Employee order by First_name ASC, Salary DESC;
SELECT * from Employee where First_name = 'John';
SELECT * from Employee where First_name = 'John';
SELECT * from Employee where First_name in ('John','Roy');
SELECT * from Employee where First_name like 'J%';
SELECT * from Employee where First_name like '%o%';
SELECT * from Employee where First_name like '%n';
SELECT * from Employee where First_name like '___n';
SELECT * from Employee where First_name like 'J___';
SELECT * from Employee where Salary > 60000;
SELECT * from Employee where Salary < 80000;
SELECT * from Employee where Salary BETWEEN 50000 and 80000;
SELECT * from Employee where First_name in ('John','Michael');
SELECT POSITION("o" IN "John") AS "Position of o in John";
SELECT MIN(Salary) as Minimum_salary from Employee;
SELECT MAX(Salary) as Maximimum_salary from Employee;
SELECT Department, COUNT(*) FROM Employee GROUP BY Department;
SELECT AVG(Salary) as "Average Salary" from Employee;